name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Svelte App
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/svelte-linksharingapp:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/svelte-linksharingapp:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/svelte-linksharingapp:latest
          cache-to: type=inline

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /srv/link-sharing-app/frontend
            docker compose pull
            docker compose up -d --build

      - name: Healthcheck
        run: |
          curl -f http://${{ secrets.SERVER_HOST }}/health || exit 1
